header
Angelica-lopez/thumbs pull request #1
Opened 2020-09-04 18:43 UTC by Angelica-lopez

2020-09-04 18:52 UTC, jlmonroy13 requested changes

2020-09-04 18:52 UTC, jlmonroy13 commented on index.html
>  </html>
siempre deja una linea en blanco al final de cada archivo

2020-09-04 18:52 UTC, jlmonroy13 commented on index.html
> +                <h1>Rule of Thumbs</h1>
esto no hace parte del nav, iria afuera

2020-09-04 18:52 UTC, jlmonroy13 commented on index.html
> +                <h3 class="nav__item-1">Past Trials</h3>
estos son anchor <a> no h3

2020-09-04 18:55 UTC, Angelica-lopez commented on index.html
> +                <h1>Rule of Thumbs</h1>
primo pero mira que eso es un a  que lleva a la misma pagina, porque no hace parte del nav?

2020-09-04 19:13 UTC, jlmonroy13 requested changes

2020-09-04 19:13 UTC, jlmonroy13 commented on index.html
> +        <div class="header__item">
Este div no se necesita

2020-09-04 19:13 UTC, jlmonroy13 commented on index.html
> +            <div class="nav__item">
Este div no se necesita

2020-09-04 19:13 UTC, jlmonroy13 commented on index.html
> +              <a href="">Past Trials</a>
y estos son los que deben tener la class nav__item

2020-09-04 19:45 UTC, jlmonroy13 requested changes

2020-09-04 19:45 UTC, jlmonroy13 commented on index.html
> +        <h1 class="header__item">Rule of Thumbs</h1>
la clase de esto seria header__title

2020-09-04 19:45 UTC, jlmonroy13 commented on index.html
> +        <nav class="nav">
La clase de esto seria  header__nav

2020-09-04 19:45 UTC, jlmonroy13 commented on index.html
> +              <a class="nav__item" href="">Past Trials</a>
la clase de esto seria header__nav-item

2020-09-04 19:45 UTC, jlmonroy13 commented on index.html
> +              <img class="nav__item-img" src="images/buscar.png" alt="Lupa">
la clase de esto es header__nav-icon

2020-09-05 14:42 UTC, jlmonroy13 approved these changes

2020-09-05 14:42 UTC, merged